require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe BaseVersionsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # BaseVersion. As you add validations to BaseVersion, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {name: "hello"}
  }

  let(:invalid_attributes) {
    {name: ""}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BaseVersionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all base_versions as @base_versions" do
      base_version = BaseVersion.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:base_versions)).to eq([base_version])
    end
  end

  describe "GET #show" do
    it "assigns the requested base_version as @base_version" do
      base_version = BaseVersion.create! valid_attributes
      get :show, {:id => base_version.to_param}, valid_session
      expect(assigns(:base_version)).to eq(base_version)
    end
  end

  describe "GET #new" do
    it "assigns a new base_version as @base_version" do
      get :new, {}, valid_session
      expect(assigns(:base_version)).to be_a_new(BaseVersion)
    end
  end

  describe "GET #edit" do
    it "assigns the requested base_version as @base_version" do
      base_version = BaseVersion.create! valid_attributes
      get :edit, {:id => base_version.to_param}, valid_session
      expect(assigns(:base_version)).to eq(base_version)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new BaseVersion" do
        expect {
          post :create, {:base_version => valid_attributes}, valid_session
        }.to change(BaseVersion, :count).by(1)
      end

      it "assigns a newly created base_version as @base_version" do
        post :create, {:base_version => valid_attributes}, valid_session
        expect(assigns(:base_version)).to be_a(BaseVersion)
        expect(assigns(:base_version)).to be_persisted
      end

      it "redirects to the created base_version" do
        post :create, {:base_version => valid_attributes}, valid_session
        expect(response).to redirect_to(BaseVersion.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved base_version as @base_version" do
        post :create, {:base_version => invalid_attributes}, valid_session
        expect(assigns(:base_version)).to be_a_new(BaseVersion)
      end

      it "re-renders the 'new' template" do
        post :create, {:base_version => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested base_version" do
        base_version = BaseVersion.create! valid_attributes
        put :update, {:id => base_version.to_param, :base_version => new_attributes}, valid_session
        base_version.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested base_version as @base_version" do
        base_version = BaseVersion.create! valid_attributes
        put :update, {:id => base_version.to_param, :base_version => valid_attributes}, valid_session
        expect(assigns(:base_version)).to eq(base_version)
      end

      it "redirects to the base_version" do
        base_version = BaseVersion.create! valid_attributes
        put :update, {:id => base_version.to_param, :base_version => valid_attributes}, valid_session
        expect(response).to redirect_to(base_version)
      end
    end

    context "with invalid params" do
      it "assigns the base_version as @base_version" do
        base_version = BaseVersion.create! valid_attributes
        put :update, {:id => base_version.to_param, :base_version => invalid_attributes}, valid_session
        expect(assigns(:base_version)).to eq(base_version)
      end

      it "re-renders the 'edit' template" do
        base_version = BaseVersion.create! valid_attributes
        put :update, {:id => base_version.to_param, :base_version => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested base_version" do
      base_version = BaseVersion.create! valid_attributes
      expect {
        delete :destroy, {:id => base_version.to_param}, valid_session
      }.to change(BaseVersion, :count).by(-1)
    end

    it "redirects to the base_versions list" do
      base_version = BaseVersion.create! valid_attributes
      delete :destroy, {:id => base_version.to_param}, valid_session
      expect(response).to redirect_to(base_versions_url)
    end
  end

end
