# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a440ae412e0d3d67ffdc15ee169b1b1e7135b60a92f85655d96c2dda53421c42428d41cdaeceb94119e27461fdbfa9538574b7a369822906faac67addf969718

test:
  secret_key_base: c9f6c86292af701d868614c9d35ec83d9fe0554364f93f45025f7c534e0383212348188c88a8070c452546a7bf1cc4eb02a0b39a065072163af6578bdddf24ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
